<?php
use Pablobae\SimpleDeliveryDate\Block\Product\DeliveryDate;

/**
 * @var $block DeliveryDate
 */

if ($block->isEnableDeliveryDate()) {
    $dates = $block->getDeliveryDates();
    if (count($dates) == 2) {
        ?>
        <div class="container-info-box delivery-date">
            <?php if ($block->showTimeLimit()) {
                $timeLimit = $block->getTimeLimit();
                ?>
                <span><?= $block->escapeHtml(__('Buy before %1 and receive your order', $timeLimit)) ?></span>

            <?php } else { ?>
                <span><?= $block->escapeHtml(__('Buy now and receive your order')) ?></span>
            <?php } ?>
            <?= $block->escapeHtml(__(' between ')) ?>
            <span
                class="deliverydate"><?= $block->escapeHtml(__($dates[0]->format('D'))) . ' ' . $block->escapeHtml(__($dates[0]->format('d'))) . ' ' . $block->escapeHtml(__('of')) . ' ' . $block->escapeHtml(__($dates[0]->format('F'))); ?></span>
            <?= $block->escapeHtml(__(' and ')) ?> <span
                class="deliverydate"><?= $block->escapeHtml(__($dates[1]->format('D'))) . ' ' . $block->escapeHtml(__($dates[1]->format('d'))) . ' ' . $block->escapeHtml(__('of')) . ' ' . $block->escapeHtml(__($dates[1]->format('F'))); ?></span>
        </div>
        <?php
    }
}
?>

